Fix python3 exception when syncing a dirty repo
it works in python2, but python3 needs an additional decode() to convert bytes object to str.

it fixes this Traceback, found randomly on some reposyncer jobs
Traceback
File "/tmp/tmpk1cicegr/reposyncer-1.0.0-py3.6.egg/reposyncer/utils.py", line 41, in run_repo
    return _Repo(os.path.join(os.getcwd(), ".repo"))._Run(list(argv))
  File "/tmp/tmpk1cicegr/gitrepo-0.2.2-py3.6.egg/repo/main.py", line 185, in _Run
    result = cmd.Execute(copts, cargs)
  File "/tmp/tmpk1cicegr/gitrepo-0.2.2-py3.6.egg/repo/subcmds/sync.py", line 822, in Execute
    if self.UpdateProjectList():
  File "/tmp/tmpk1cicegr/gitrepo-0.2.2-py3.6.egg/repo/subcmds/sync.py", line 564, in UpdateProjectList
    if project.IsDirty():
  File "/tmp/tmpk1cicegr/gitrepo-0.2.2-py3.6.egg/repo/project.py", line 781, in IsDirty
    if self.work_git.DiffZ('diff-index', '-M', '--cached', HEAD):
  File "/tmp/tmpk1cicegr/gitrepo-0.2.2-py3.6.egg/repo/project.py", line 2668, in DiffZ
    out = iter(out[:-1].split('\0'))  # pylint: disable=W1401
TypeError: a bytes-like object is required, not 'str'